#MOUSEKEY_ENABLE = yes    # Mouse keys
UNICODEMAP_ENABLE = yes
#UNICODE_ENABLE = yes
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
#DYNAMIC_TAPPING_TERM_ENABLE = yes